## **檢查Word/Excel loading後的結果**

### Read Word file

In [1]:

# 讓 notebook 能 import src 套件
import os, sys
from pathlib import Path


sys.path.append(str((Path.cwd().parent).resolve()))

%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
from pathlib import Path
from adapters.word_table_adapter import WordTableAdapter
from adapters.excel_table_adapter import ExcelTableAdapter

In [3]:
BASE_DIR   = Path(r"C:\Users\ai\Desktop\smithfu\repositories\lazy-tools\docx_xlsx_comparator")
INPUT_DIR  = BASE_DIR / "input"
OUTPUT_DIR = BASE_DIR / "output"

In [4]:
word_path =  INPUT_DIR / "03.資通系統防護基準_佐證資料_農業統計資料管理系統_(普)_(奕祥資訊股份有限公司) v4_A3版_修3.docx"
word_adapter = WordTableAdapter(word_path)
word_df = word_adapter.load()
# Note: Maybe there's some newline characters '\n' in the column names, we need to remove them.
normalized_columns = [col.replace("\n", "") for col in word_df.columns]
word_df.columns = normalized_columns

Document has 1 tables.

In [5]:
word_df

,類別,安全控制措施,符合性或不適用情況說明,廠商完成此安控措施提供之佐證資料(系統、程式碼截圖)、管理程序表單或管理措施等說明
0,1-1.帳號管理,建立帳號管理機制，包含帳號之申請、建立、修改、啟用、停用及刪除之程序。,帳號權限異動時填列申請表，並至後臺系統維護帳號資料。\n帳號申請、修改權限與停用均需經事先申...,帳號管理規範\n系統帳號／權限異動申請表\n\n帳號異動申請表。
1,1-1.帳號管理,已逾期之臨時或緊急帳號應刪除或禁用。,帳號由管理人派發管理，除每半年之正式帳號清查，臨時或緊急帳號無需求後會由管理人隨即停用。,如未管理臨時或緊急帳號，或是雖訂定相關管理規範卻未落實執行，則未符合此項控制措施\n抽查資通...
2,1-1.帳號管理,資通系統閒置帳號應禁用。,每半年之正式帳號清查，若超過半年未使用之帳號會將之停用。,相關管理規範\n使用者操作日誌\n查詢所有使用者最後一次登入日期時間，(若無法查詢，應請廠商...
3,1-1.帳號管理,定期審核資通系統帳號之申請、建立、修改、啟用、停用及刪除。,每半年審查帳號使用狀況，並至後臺系統維護帳號資料。,帳號權限審查表\n宜抽查資通系統現有帳號之使用情況， 並與帳號異動紀錄比對，以驗證機關帳號審...
4,1-2.最小權限,採最小權限原則，僅允許使用者(或代表使用者行為之程序)依機關任務及業務功能，完成指派任務所需...,透過每半年之正式帳號清查，檢查帳號是否具管理員權限。\n\n帳號與權限授予僅限業務必要之使用者。,抽查發現明確違反最小權限原則之使用行為，則未符合此項控制措施，如使用者所配發之帳號權限， 明...
5,1-3.遠端存取,對於每一種允許之遠端存取類型，均應先取得授權，建立使用限制、組態需求、連線需求及文件化。,系統主機置於MOA機房者，主機OS與DB存取由機房防火牆管控，僅限機關內網可遠端連線，且須依...,測試案例:\n先使用測試帳號登入系統並存取功能頁面\n將頁面網址記錄下來\n登出帳號\n在未...
6,1-3.遠端存取,使用者之權限檢查作業應於伺服器端完成。,使用者登入系統時，帳號及密碼等資訊存在資料庫伺服器端，密碼採不可逆之加密方式儲存，以SQL指...,使用者進行遠端存取時， 如系統未於伺服器端實作授權檢查作業，則未符合此項控制措施\n以測試案...
7,1-3.遠端存取,應監控遠端存取機關內部網段或資通系統後臺之連線。,系統主機置於MOA機房者，連線存取均透過跳板軟體及側錄機制監控。\n系統提供系統維護紀錄，紀...,系統監控管理程序、系統監控紀錄\n如未監控遠端存取機關內部網段或資通系統後臺之連線，則未符合...
8,1-3.遠端存取,應採用加密機制。,網站伺服器使用TLS加密方式連線，不允許HTTP進行網頁存取。,使用 HTTP 進行網頁存取，或在未經 VPN 連線存取功能頁面，系統應拒絕連線或強制導向至...
9,1-3.遠端存取,遠端存取之來源應為機關已預先定義及管理之存取控制點。,系統主機置於MOA機房者，主機OS與DB存取由機房防火牆管控，僅限機關內網可遠端連線，且須依...,網管規範，防火牆規則、系統連線日誌\n系統限制須為預先建立之使用者方可登入後臺管理系統中。\...
10,2-1.記錄事件,訂定日誌之記錄時間週期及留存政策，並保留日誌至少六個月。,日誌保存在資料庫，紀錄使用者相關維護動作，並確保保存六個月。,資通系統日誌， 如檢視資通系統伺服器日誌、資料庫日誌檔案及伺服器主機作業系統日誌等，確認已包...
11,2-1.記錄事件,確保資通系統有記錄特定事件之功能，並決定應記錄之特定資通系統事件。,"日誌紀錄包括系統執行紀錄,如登入失敗或登出紀錄等, 請見佐證擷圖。",系統日誌，需包含特定資通系統事件紀錄\n觸發特定事件(輸入錯誤通行碼導致身分驗證失敗)以產生...
12,2-1.記錄事件,應記錄資通系統管理者帳號所執行之各項功能。,由系統後臺提供管理者維護紀錄，記錄相關維護動作。,資通系統管理者帳號所執行之各項功能紀錄\n抽查資通系統日誌，其中已留存之管理者帳號功能執行紀...
13,2-2.日誌紀錄內容,資通系統產生之日誌應包含事件類型、發生時間、發生位置及任何與事件相關之使用者身分識別等資訊，...,由系統後臺提供系統管理者維護紀錄，包含變更項目、使用者、動作、變更日期、時間、登入IP、詳細...,抽查日誌格式\n檢視特定事件或管理者行為之Log紀錄，應包含關鍵資訊並具備一致格式\n系統執...
14,2-3.日誌儲存容量,依據日誌儲存需求，配置所需之儲存容量。,MOA機房統一收容OS/DB 日誌。\n系統維護紀錄存放於資料庫中，磁碟空間可依資料量自動擴...,資通系統未規劃足夠之日誌儲存容量，使得儲存空間滿載而危害日誌處理機制，或未有其他有效配套措施...
15,2-4.日誌處理失效之回應,資通系統於日誌處理失效時，應採取適當之行動。,系統維護紀錄存放於資料庫中，磁碟空間接近上限時，監控系統即通知相關負責人員進行系統資源調整，...,未分析評估任何可能造成資通系統日誌處理失效原因，或未規劃日誌處理失效因應措施，則未符合此控制...
16,2-5.時戳及校時,資通系統應使用系統內部時鐘產生日誌所需時戳，並可以對應到世界協調時間(UTC)或格林威治標準...,"系統主機置於MOA機房者, 主機皆設定與NTP server校時產生時戳。",如資通系統日誌內未留存時戳，或時戳非由系統內部時鐘所產生而無法對應到 UTC 或 GMT 時...
17,2-5.時戳及校時,系統內部時鐘應定期與基準時間源進行同步。,"系統主機置於MOA機房者, 主機皆設定與NTP server校時產生時戳。",系統內部時鐘未定期成功與基準時間源進行同步，則未符合此項控制措施\n如:伺服器可以跟AD s...
18,2-6.日誌資訊之保護,對日誌之存取管理，僅限於有權限之使用者。,"系統主機置於MOA機房者, 僅限系統管理者及主機管理者有權限。\n\n僅限系統管理者有權限。",如未針對資通系統日誌進行存取管理， 或允許非權責人員任意調閱，則未符合此控制措施\n嘗試利用...
19,3-1.資料備份,訂定資料可容忍損失之時間要求。,本系統定義可容忍資料損失時間為24小時,程序或文件紀錄(如BIA衝擊分析表)：系統可容忍資料損失之時間要求\n防護需求分級評估表：
20,3-1.資料備份,執行資料備份。,備有svn源碼及版本管理，並由備份系統進行備份。\n註：MOA機房提供整機儲存快照，3地進行...,備份原則(backup policy)\n系統源碼與相關重要資料備份所在之畫面擷圖\n（相關...
21,3-2.系統備援,訂定資通系統從中斷後至重新恢復服務之最大可容忍中斷時間要求。,本系統最大可容忍中斷時間要求為72小時。,程序或文件紀錄(如BIA衝擊分析表)：系統可容忍資料損失之時間要求\n防護需求分級評估表：
22,4-1.使用者之識別與鑑別,資通系統應識別及鑑別使用者，並禁止使用者使用共用帳號。,每一系統使用者皆獨立擁有各自帳號。,畫面擷圖：身分驗證功能\n檢視資通系統日誌，查找是否存在共用帳號之行為\n日誌顯示某使用者帳...
23,4-2.身分驗證管理,使用預設密碼初次登入系統時，應於登入後立即變更。,首次登入後，系統即強制要求變更密碼。,系統登入時強制要求修改密碼。
24,4-2.身分驗證管理,身分驗證相關資訊不以明文傳輸。,網站填報使用者密碼資訊透過TLS加密傳輸。,網站TLS憑證
25,4-2.身分驗證管理,具備帳戶鎖定機制，帳號登入進行身分驗證失敗達五次後，至少十五分鐘內不允許該帳號繼續嘗試登入或...,帳號登入失敗３次即鎖定，須由系統管理者解除鎖定。,登入系統時帳號停用。
26,4-2.身分驗證管理,使用密碼進行驗證時，應強制最低密碼複雜度；依機關密碼效期規定變更密碼。,使用者密碼長度須8碼，密碼內容須包含英文、數字及符號，每3個月須更新密碼。,修改密碼時不符規則之訊息。
27,4-2.身分驗證管理,密碼變更時，至少不可以與前三次使用過之密碼相同。,變更密碼時，系統預設不可與前三次密碼相同。,密碼不可於前3次相同之訊息。
28,4-2.身分驗證管理,前兩項所定措施，對外部使用者，機關得自行規範辦理。,僅限部內以及申請機關進行使用。,說明:非內部使用者包含所有未明確涵蓋於機關內部使用者的資通系統使用者，如一般民眾等\n\n\...
29,4-3.鑑別資訊保護,資通系統應遮蔽鑑別過程中之資訊。,輸入密碼欄位均使用星號顯示。,畫面擷圖：資通系統預設遮蔽密碼字元、需要輸入密碼的頁面，除非使用者另行設定(如勾選「顯示密碼...
30,5-1.系統發展生命週期需求階段,針對系統安全需求(含機密性、可用性、完整性)進行確認。,本系統安全等級為「普」，廠商依照需求開發系統。,資通安全研究院「資通系統委外開發 RFP 資安需求範本-附件 1 資通系統資安需求項目查檢表...
31,5-3.系統發展生命週期開發階段,應針對安全需求實作必要控制措施。,契約要求開發廠商開發時需符合資通系統防護基準安控措施要求。,資通系統需求規格文件及驗收報告\n資通系統防護基準之安全規範項目符合情形\n資通系統防護基準...
32,5-3.系統發展生命週期開發階段,應注意避免軟體常見漏洞及實作必要控制措施。,針對OWASP風險訂定設計規則。,確認系統已防範 OWASP Top 10 等安全漏洞，常見控制措施包含：\n系統安全開發教育...
33,5-3.系統發展生命週期開發階段,發生錯誤時，使用者頁面僅顯示簡短錯誤訊息及代碼，不包含詳細之錯誤訊息。,發生錯誤時，使用者頁面僅顯示簡短錯誤訊息。,畫面擷圖：嘗試產生錯誤操作，檢視頁面所呈現之訊息\n如存取不存在的網址、輸入錯誤數值等\n系...
34,5-4.系統發展生命週期測試階段,執行「弱點掃描」安全檢測。,於上線前提交弱掃報告，之後每季執行弱點掃描。,弱點掃描報告及修補紀錄\n弱點掃描報告\n\n\n上述弱掃報告符合系統上線需求，並於下一季弱...
35,5-5.系統發展生命週期部署與維運階段,於部署環境中應針對相關資通安全威脅，進行更新與修補。,系統主機置於MOA機房者，由資訊司機房統一管理。\n定期安裝伺服主機安全性更新,如資通系統未更新與修補部署環境中的軟體元件，包含作業系統、 資通系統伺服器、執行環境以及函式...
36,5-5.系統發展生命週期部署與維運階段,識別並關閉不必要服務及埠口。,系統主機置於MOA機房者，由資訊司機房統一管理，系統建置接檢附防火牆申請，驗證並僅開放必要的...,允許使用者透過網路連接至非必要系統服務及埠口，則未符合此控制措施\n網路服務申請單
37,5-5.系統發展生命週期部署與維運階段,資通系統不使用預設密碼。,所有設備於啟用前均已變更原廠預設管理帳號密碼，並關閉不必要之預設帳號。,系統登入時強制要求修改密碼。
38,5-5.系統發展生命週期部署與維運階段,執行系統源碼備份。,SVN版控備份\n註：MOA機房統一管理，系統皆由版控軟體管理，並經由版控上版。,備份執行方式及驗證備份是否完整，若無則未符合此控制措施\n\n（相關管理制度由資訊中心控管，...
39,5-6.系統發展生命週期委外階段,資通系統開發如委外辦理，應將系統發展生命週期各階段依等級將安全需求(含機密性、可用性、完整性...,契約「第二十二條 資訊安全」已納入相關安全需求。,委外契約\n契約書
40,5-7.獲得程序,識別資通系統使用之第三方軟體、服務函式庫或其他元件。,提供應用系統軟體物料清單,SBOM\n軟體物料清單
41,5-8.系統文件,應儲存與管理系統發展生命週期之相關文件。,儲存及管理「程式規格書」、「系統管理手冊」、「使用者手冊」等文件，廠商於期末交付修訂版。,系統發展生命週期管理文件\n\n工作需求說明書。
42,7-1.漏洞修復,系統之漏洞修復應測試有效性及潛在影響，並定期更新。,於上線前提交弱掃報告，之後每季執行弱點掃描。,資通系統漏洞修補後測試報告\n弱點掃描報告
43,7-2.資通系統監控,發現資通系統有被入侵跡象時，應通報機關特定人員。,系統主機置於MOA機房者，由資訊司機房SOC/EDR/網頁監控機制監控管理，異常時通知機房與...,入侵偵測系統、入侵防禦系統、惡意程式碼防護軟體、掃描工具，稽核紀錄監控軟體、網路監控軟體等\...
44,7-3.軟體及資訊完整性,使用者輸入資料合法性檢查應置放於應用系統伺服器端。,網站輸入資料驗證於伺服器端或瀏覽器端+伺服器端進行處理。,如資通系統未於資通系統伺服器端實作使用者輸入資料合法性檢查，則未符合此控制措施\n在滲透測試...

### Read Excel file

In [6]:
excel_path =  INPUT_DIR / "02.防護基準評估表.xlsx"
excel_adapter = ExcelTableAdapter(excel_path)
excel_df = excel_adapter.load()

In [7]:
excel_df

,構面,構面說明,類別,類別說明,安全控制措施,安全控制措施說明,控制措施符合度,符合性或不適用情況說明,預計改善作為,預計完成日期,已完成日期
0,1,存取控制,1,帳號管理,1,建立帳號管理機制，包含帳號之申請、建立、修改、啟用、停用及刪除之程序。,全部符合,帳號權限異動時填列申請表，並至後臺系統維護帳號資料。\n帳號申請、修改權限與停用均需經事先申...,NaN,NaN,NaN
1,1,存取控制,1,帳號管理,2,已逾期之臨時或緊急帳號應刪除或禁用。,全部符合,帳號由管理人派發管理，除每半年之正式帳號清查，臨時或緊急帳號無需求後會由管理人隨即停用。,NaN,NaN,NaN
2,1,存取控制,1,帳號管理,3,資通系統閒置帳號應禁用。,全部符合,每半年之正式帳號清查，若超過半年未使用之帳號會將之停用。,NaN,NaN,NaN
3,1,存取控制,1,帳號管理,4,定期審核資通系統帳號之申請、建立、修改、啟用、停用及刪除。,全部符合,每半年審查帳號使用狀況，並至後臺系統維護帳號資料。,NaN,NaN,NaN
4,1,存取控制,2,最小權限,1,採最小權限原則，僅允許使用者(或代表使用者行為之程序)依機關任務及業務功能，完成指派任務所需...,全部符合,透過每半年之正式帳號清查，檢查帳號是否具管理員權限。\n帳號與權限授予僅限業務必要之使用者。,NaN,NaN,NaN
5,1,存取控制,3,遠端存取,1,對於每一種允許之遠端存取類型，均應先取得授權，建立使用限制、組態需求、連線需求及文件化。,全部符合,系統主機置於MOA機房者，主機OS與DB存取由機房防火牆管控，僅限機關內網可遠端連線，且須依...,NaN,NaN,1141231.0
6,1,存取控制,3,遠端存取,2,使用者之權限檢查作業應於伺服器端完成。,全部符合,使用者登入系統時，帳號及密碼等資訊存在資料庫伺服器端，密碼採不可逆之加密方式儲存，以SQL指...,NaN,NaN,1141231.0
7,1,存取控制,3,遠端存取,3,應監控遠端存取機關內部網段或資通系統後臺之連線。,全部符合,系統主機置於MOA機房者，連線存取均透過跳板軟體及側錄機制監控。\n系統提供系統維護紀錄，紀...,NaN,NaN,1141231.0
8,1,存取控制,3,遠端存取,4,應採用加密機制。,全部符合,網站伺服器使用TLS加密方式連線，不允許HTTP進行網頁存取。,NaN,NaN,1141231.0
9,1,存取控制,3,遠端存取,5,遠端存取之來源應為機關已預先定義及管理之存取控制點。,全部符合,系統主機置於MOA機房者，主機OS與DB存取由機房防火牆管控，僅限機關內網可遠端連線，且須依...,NaN,NaN,1141231.0
10,2,事件日誌與可歸責性,1,記錄事件,1,訂定日誌之記錄時間週期及留存政策，並保留日誌至少六個月。,全部符合,日誌保存在資料庫，紀錄使用者相關維護動作，並確保保存六個月。,NaN,NaN,1141231.0
11,2,事件日誌與可歸責性,1,記錄事件,2,確保資通系統有記錄特定事件之功能，並決定應記錄之特定資通系統事件。,全部符合,"日誌紀錄包括系統執行紀錄,如登入失敗或登出紀錄等, 請見佐證擷圖。",NaN,NaN,NaN
12,2,事件日誌與可歸責性,1,記錄事件,3,應記錄資通系統管理者帳號所執行之各項功能。,全部符合,由系統後臺提供管理者維護紀錄，記錄相關維護動作。,NaN,NaN,NaN
13,2,事件日誌與可歸責性,2,日誌紀錄內容,1,資通系統產生之日誌應包含事件類型、發生時間、發生位置及任何與事件相關之使用者身分識別等資訊，...,全部符合,由系統後臺提供系統管理者維護紀錄，包含變更項目、使用者、動作、變更日期、時間、登入IP、詳細...,NaN,NaN,NaN
14,2,事件日誌與可歸責性,3,日誌儲存容量,1,依據日誌儲存需求，配置所需之儲存容量。,全部符合,MOA機房統一收容OS/DB 日誌。\n系統維護紀錄存放於資料庫中，磁碟空間可依資料量自動擴...,NaN,NaN,1141231.0
15,2,事件日誌與可歸責性,4,日誌處理失效之回應,1,資通系統於日誌處理失效時，應採取適當之行動。,全部符合,系統維護紀錄存放於資料庫中，磁碟空間接近上限時，監控系統即通知相關負責人員進行系統資源調整，...,NaN,NaN,1141231.0
16,2,事件日誌與可歸責性,5,時戳及校時,1,資通系統應使用系統內部時鐘產生日誌所需時戳，並可以對應到世界協調時間(UTC)或格林威治標準...,全部符合,"系統主機置於MOA機房者, 主機皆設定與NTP server校時產生時戳。",NaN,NaN,1141231.0
17,2,事件日誌與可歸責性,5,時戳及校時,2,系統內部時鐘應定期與基準時間源進行同步。,全部符合,"系統主機置於MOA機房者, 主機皆設定與NTP server校時產生時戳。",NaN,NaN,1141231.0
18,2,事件日誌與可歸責性,6,日誌資訊之保護,1,對日誌之存取管理，僅限於有權限之使用者。,全部符合,"系統主機置於MOA機房者, 僅限系統管理者及主機管理者有權限。\n\n僅限系統管理者有權限。",NaN,NaN,1141231.0
19,3,營運持續計畫,1,資料備份,1,訂定資料可容忍損失之時間要求。,全部符合,本系統定義可容忍資料損失時間為24小時,NaN,NaN,NaN
20,3,營運持續計畫,1,資料備份,2,執行資料備份。,全部符合,備有svn源碼及版本管理，並由備份系統進行備份。\n註：MOA機房提供整機儲存快照，3地進行...,NaN,NaN,1141231.0
21,3,營運持續計畫,2,系統備援,1,訂定資通系統從中斷後至重新恢復服務之最大可容忍中斷時間要求。,全部符合,本系統最大可容忍中斷時間要求為72小時。,NaN,NaN,NaN
22,4,識別與鑑別,1,使用者之識別與鑑別,1,資通系統應識別及鑑別使用者，並禁止使用者使用共用帳號。,全部符合,每一系統使用者皆獨立擁有各自帳號。,NaN,NaN,NaN
23,4,識別與鑑別,2,身分驗證管理,1,使用預設密碼初次登入系統時，應於登入後立即變更。,全部符合,首次登入後，系統即強制要求變更密碼。,NaN,NaN,NaN
24,4,識別與鑑別,2,身分驗證管理,2,身分驗證相關資訊不以明文傳輸。,全部符合,網站填報使用者密碼資訊透過TLS加密傳輸。,NaN,NaN,NaN
25,4,識別與鑑別,2,身分驗證管理,3,具備帳戶鎖定機制，帳號登入進行身分驗證失敗達五次後，至少十五分鐘內不允許該帳號繼續嘗試登入或...,全部符合,帳號登入失敗３次即鎖定，須由系統管理者解除鎖定。,NaN,NaN,NaN
26,4,識別與鑑別,2,身分驗證管理,4,使用密碼進行驗證時，應強制最低密碼複雜度；依機關密碼效期規定變更密碼。,全部符合,使用者密碼長度須8碼，密碼內容須包含英文、數字及符號，每3個月須更新密碼。,NaN,NaN,NaN
27,4,識別與鑑別,2,身分驗證管理,5,密碼變更時，至少不可以與前三次使用過之密碼相同。,全部符合,變更密碼時，系統預設不可與前三次密碼相同。,NaN,NaN,NaN
28,4,識別與鑑別,2,身分驗證管理,6,前兩項所定措施，對外部使用者，機關得自行規範辦理。,全部符合,僅限部內以及申請機關進行使用。,NaN,NaN,NaN
29,4,識別與鑑別,3,鑑別資訊保護,1,資通系統應遮蔽鑑別過程中之資訊。,全部符合,輸入密碼欄位均使用星號顯示。,NaN,NaN,NaN
30,5,系統與服務獲得,1,系統發展生命週期需求階段,1,針對系統安全需求(含機密性、可用性、完整性)進行確認。,全部符合,本系統安全等級為「普」，廠商依照需求開發系統。,NaN,NaN,NaN
31,5,系統與服務獲得,3,系統發展生命週期開發階段,1,應針對安全需求實作必要控制措施。,全部符合,契約要求開發廠商開發時需符合資通系統防護基準安控措施要求。,NaN,NaN,NaN
32,5,系統與服務獲得,3,系統發展生命週期開發階段,2,應注意避免軟體常見漏洞及實作必要控制措施。,全部符合,針對OWASP風險訂定設計規則。,NaN,NaN,NaN
33,5,系統與服務獲得,3,系統發展生命週期開發階段,3,發生錯誤時，使用者頁面僅顯示簡短錯誤訊息及代碼，不包含詳細之錯誤訊息。,全部符合,發生錯誤時，使用者頁面僅顯示簡短錯誤訊息。,NaN,NaN,NaN
34,5,系統與服務獲得,4,系統發展生命週期測試階段,1,執行「弱點掃描」安全檢測。,全部符合,於上線前提交弱掃報告，之後每季執行弱點掃描。,NaN,NaN,1141106.0
35,5,系統與服務獲得,5,系統發展生命週期部署與維運階段,1,於部署環境中應針對相關資通安全威脅，進行更新與修補。,全部符合,系統主機置於MOA機房者，由資訊司機房統一管理。\n定期安裝伺服主機安全性更新,NaN,NaN,NaN
36,5,系統與服務獲得,5,系統發展生命週期部署與維運階段,2,識別並關閉不必要服務及埠口。,全部符合,系統主機置於MOA機房者，由資訊司機房統一管理，系統建置接檢附防火牆申請，驗證並僅開放必要的...,NaN,NaN,1141231.0
37,5,系統與服務獲得,5,系統發展生命週期部署與維運階段,3,資通系統不使用預設密碼。,全部符合,所有設備於啟用前均已變更原廠預設管理帳號密碼，並關閉不必要之預設帳號。,NaN,NaN,NaN
38,5,系統與服務獲得,5,系統發展生命週期部署與維運階段,4,執行系統源碼備份。,全部符合,SVN版控備份\n註：MOA機房統一管理，系統皆由版控軟體管理，並經由版控上版。,NaN,NaN,NaN
39,5,系統與服務獲得,6,系統發展生命週期委外階段,1,資通系統開發如委外辦理，應將系統發展生命週期各階段依等級將安全需求(含機密性、可用性、完整性...,全部符合,契約「第二十二條 資訊安全」已納入相關安全需求。,NaN,NaN,NaN
40,5,系統與服務獲得,7,獲得程序,1,識別資通系統使用之第三方軟體、服務函式庫或其他元件。,全部符合,提供應用系統軟體物料清單,NaN,NaN,1141231.0
41,5,系統與服務獲得,8,系統文件,1,應儲存與管理系統發展生命週期之相關文件。,全部符合,儲存及管理「程式規格書」、「系統管理手冊」、「使用者手冊」等文件，廠商於期末交付修訂版。,NaN,NaN,NaN
42,7,系統與資訊完整性,1,漏洞修復,1,系統之漏洞修復應測試有效性及潛在影響，並定期更新。,全部符合,於上線前提交弱掃報告，之後每季執行弱點掃描。,NaN,NaN,NaN
43,7,系統與資訊完整性,2,資通系統監控,1,發現資通系統有被入侵跡象時，應通報機關特定人員。,全部符合,系統主機置於MOA機房者，由資訊司機房SOC/EDR/網頁監控機制監控管理，異常時通知機房與...,NaN,NaN,1141231.0
44,7,系統與資訊完整性,3,軟體及資訊完整性,1,使用者輸入資料合法性檢查應置放於應用系統伺服器端。,全部符合,網站輸入資料驗證於伺服器端或瀏覽器端+伺服器端進行處理。,NaN,NaN,NaN

### Find common column

In [8]:
word_columns = set(word_df.columns)
excel_columns = set(excel_df.columns)

print(word_columns)
print(excel_columns)

common_columns = list(word_columns & excel_columns)
common_columns

{'安全控制措施', '廠商完成此安控措施提供之佐證資料(系統、程式碼截圖)、管理程序表單或管理措施等說明', '符合性或不適用情況說明', '類別'}
{'類別', '預計完成日期', '預計改善作為', '構面說明', '類別說明', '控制措施符合度', '安全控制措施', '已完成日期', '安全控制措施說明', '構面', '符合性或不適用情況說明'}

['安全控制措施', '符合性或不適用情況說明', '類別']

In [9]:
## Excel preprocessing : 1. Drop '安全控制措施', 2. Drop rename '安全控制措施說明' as '安全控制措施'
excel_df = (
            excel_df
            .drop(columns=["安全控制措施"])
            .rename(columns={"安全控制措施說明": "安全控制措施"})
            .reindex(columns=excel_df.columns))

### Choose the main option to list the common raws

In [10]:
def get_common_row_keys(word_df, excel_df, key_col: str):
    word_keys = set(word_df[key_col].dropna().astype(str).str.strip())
    print(word_keys)
    excel_keys = set(excel_df[key_col].dropna().astype(str).str.strip())
    print(excel_keys)
    common_keys = list(word_keys & excel_keys)
    return common_keys

In [11]:
key_col = "安全控制措施"

common_row_keys = get_common_row_keys(word_df, excel_df, key_col)
common_row_keys

{'訂定資通系統從中斷後至重新恢復服務之最大可容忍中斷時間要求。', '遠端存取之來源應為機關已預先定義及管理之存取控制點。', '應儲存與管理系統發展生命週期之相關文件。', '發現資通系統有被入侵跡象時，應通報機關特定人員。', '資通系統不使用預設密碼。', '已逾期之臨時或緊急帳號應刪除或禁用。', '應針對安全需求實作必要控制措施。', '識別並關閉不必要服務及埠口。', '對於每一種允許之遠端存取類型，均應先取得授權，建立使用限制、組態需求、連線需求及文件化。', '對日誌之存取管理，僅限於有權限之使用者。', '應注意避免軟體常見漏洞及實作必要控制措施。', '應記錄資通系統管理者帳號所執行之各項功能。', '執行系統源碼備份。', '資通系統開發如委外辦理，應將系統發展生命週期各階段依等級將安全需求(含機密性、可用性、完整性)納入委外契約。', '識別資通系統使用之第三方軟體、服務函式庫或其他元件。', '針對系統安全需求(含機密性、可用性、完整性)進行確認。', '應監控遠端存取機關內部網段或資通系統後臺之連線。', '具備帳戶鎖定機制，帳號登入進行身分驗證失敗達五次後，至少十五分鐘內不允許該帳號繼續嘗試登入或使用機關自建之失敗驗證機制。', '定期審核資通系統帳號之申請、建立、修改、啟用、停用及刪除。', '執行資料備份。', '於部署環境中應針對相關資通安全威脅，進行更新與修補。', '前兩項所定措施，對外部使用者，機關得自行規範辦理。', '資通系統應遮蔽鑑別過程中之資訊。', '應採用加密機制。', '訂定資料可容忍損失之時間要求。', '資通系統產生之日誌應包含事件類型、發生時間、發生位置及任何與事件相關之使用者身分識別等資訊，採用單一日誌機制，確保輸出格式之一致性，並應依資通安全政策及法規要求納入其他相關資訊。', '使用者之權限檢查作業應於伺服器端完成。', '訂定日誌之記錄時間週期及留存政策，並保留日誌至少六個月。', '系統之漏洞修復應測試有效性及潛在影響，並定期更新。', '建立帳號管理機制，包含帳號之申請、建立、修改、啟用、停用及刪除之程序。', '資通系統閒置帳號應禁用。', '資通系統於日誌處理失效時，應採取適當之行動。', '依據日誌儲存需求，配置所需之儲存容量。', '資通系統應識別及鑑別使用者，並禁止使用者使用共用帳號。', '執行「弱點掃描」安全檢測。', '使用密碼進行驗證時，應強制最低密碼複雜度；依機關密碼效期規定變更密碼。', '身分驗證相關資訊不以明文傳輸。', '採最小權限原則，僅允許使用者(或代表使用者行為之程序)依機關任務及業務功能，完成指派任務所需之授權存取。', '確保資通系統有記錄特定事件之功能，並決定應記錄之特定資通系統事件。', '資通系統應使用系統內部時鐘產生日誌所需時戳，並可以對應到世界協調時間(UTC)或格林威治標準時間(GMT)。', '系統內部時鐘應定期與基準時間源進行同步。', '發生錯誤時，使用者頁面僅顯示簡短錯誤訊息及代碼，不包含詳細之錯誤訊息。', '密碼變更時，至少不可以與前三次使用過之密碼相同。', '使用者輸入資料合法性檢查應置放於應用系統伺服器端。', '使用預設密碼初次登入系統時，應於登入後立即變更。'}
{'訂定資通系統從中斷後至重新恢復服務之最大可容忍中斷時間要求。', '遠端存取之來源應為機關已預先定義及管理之存取控制點。', '應儲存與管理系統發展生命週期之相關文件。', '發現資通系統有被入侵跡象時，應通報機關特定人員。', '資通系統不使用預設密碼。', '已逾期之臨時或緊急帳號應刪除或禁用。', '應針對安全需求實作必要控制措施。', '識別並關閉不必要服務及埠口。', '對於每一種允許之遠端存取類型，均應先取得授權，建立使用限制、組態需求、連線需求及文件化。', '對日誌之存取管理，僅限於有權限之使用者。', '應注意避免軟體常見漏洞及實作必要控制措施。', '應記錄資通系統管理者帳號所執行之各項功能。', '執行系統源碼備份。', '資通系統開發如委外辦理，應將系統發展生命週期各階段依等級將安全需求(含機密性、可用性、完整性)納入委外契約。', '識別資通系統使用之第三方軟體、服務函式庫或其他元件。', '針對系統安全需求(含機密性、可用性、完整性)進行確認。', '應監控遠端存取機關內部網段或資通系統後臺之連線。', '具備帳戶鎖定機制，帳號登入進行身分驗證失敗達五次後，至少十五分鐘內不允許該帳號繼續嘗試登入或使用機關自建之失敗驗證機制。', '定期審核資通系統帳號之申請、建立、修改、啟用、停用及刪除。', '執行資料備份。', '於部署環境中應針對相關資通安全威脅，進行更新與修補。', '前兩項所定措施，對外部使用者，機關得自行規範辦理。', '資通系統應遮蔽鑑別過程中之資訊。', '應採用加密機制。', '訂定資料可容忍損失之時間要求。', '資通系統產生之日誌應包含事件類型、發生時間、發生位置及任何與事件相關之使用者身分識別等資訊，採用單一日誌機制，確保輸出格式之一致性，並應依資通安全政策及法規要求納入其他相關資訊。', '使用者之權限檢查作業應於伺服器端完成。', '訂定日誌之記錄時間週期及留存政策，並保留日誌至少六個月。', '系統之漏洞修復應測試有效性及潛在影響，並定期更新。', '建立帳號管理機制，包含帳號之申請、建立、修改、啟用、停用及刪除之程序。', '資通系統閒置帳號應禁用。', '資通系統於日誌處理失效時，應採取適當之行動。', '依據日誌儲存需求，配置所需之儲存容量。', '資通系統應識別及鑑別使用者，並禁止使用者使用共用帳號。', '執行「弱點掃描」安全檢測。', '使用密碼進行驗證時，應強制最低密碼複雜度；依機關密碼效期規定變更密碼。', '身分驗證相關資訊不以明文傳輸。', '採最小權限原則，僅允許使用者(或代表使用者行為之程序)依機關任務及業務功能，完成指派任務所需之授權存取。', '確保資通系統有記錄特定事件之功能，並決定應記錄之特定資通系統事件。', '資通系統應使用系統內部時鐘產生日誌所需時戳，並可以對應到世界協調時間(UTC)或格林威治標準時間(GMT)。', '系統內部時鐘應定期與基準時間源進行同步。', '發生錯誤時，使用者頁面僅顯示簡短錯誤訊息及代碼，不包含詳細之錯誤訊息。', '密碼變更時，至少不可以與前三次使用過之密碼相同。', '使用者輸入資料合法性檢查應置放於應用系統伺服器端。', '使用預設密碼初次登入系統時，應於登入後立即變更。'}

['訂定資通系統從中斷後至重新恢復服務之最大可容忍中斷時間要求。',
 '遠端存取之來源應為機關已預先定義及管理之存取控制點。',
 '應儲存與管理系統發展生命週期之相關文件。',
 '發現資通系統有被入侵跡象時，應通報機關特定人員。',
 '資通系統不使用預設密碼。',
 '已逾期之臨時或緊急帳號應刪除或禁用。',
 '應針對安全需求實作必要控制措施。',
 '識別並關閉不必要服務及埠口。',
 '對於每一種允許之遠端存取類型，均應先取得授權，建立使用限制、組態需求、連線需求及文件化。',
 '對日誌之存取管理，僅限於有權限之使用者。',
 '應注意避免軟體常見漏洞及實作必要控制措施。',
 '應記錄資通系統管理者帳號所執行之各項功能。',
 '執行系統源碼備份。',
 '資通系統開發如委外辦理，應將系統發展生命週期各階段依等級將安全需求(含機密性、可用性、完整性)納入委外契約。',
 '識別資通系統使用之第三方軟體、服務函式庫或其他元件。',
 '針對系統安全需求(含機密性、可用性、完整性)進行確認。',
 '應監控遠端存取機關內部網段或資通系統後臺之連線。',
 '具備帳戶鎖定機制，帳號登入進行身分驗證失敗達五次後，至少十五分鐘內不允許該帳號繼續嘗試登入或使用機關自建之失敗驗證機制。',
 '定期審核資通系統帳號之申請、建立、修改、啟用、停用及刪除。',
 '執行資料備份。',
 '於部署環境中應針對相關資通安全威脅，進行更新與修補。',
 '前兩項所定措施，對外部使用者，機關得自行規範辦理。',
 '資通系統應遮蔽鑑別過程中之資訊。',
 '應採用加密機制。',
 '訂定資料可容忍損失之時間要求。',
 '資通系統產生之日誌應包含事件類型、發生時間、發生位置及任何與事件相關之使用者身分識別等資訊，採用單一日誌機制，確保輸出格式之一致性，並應依資通安全政策及法規要求納入其他相關資訊。',
 '使用者之權限檢查作業應於伺服器端完成。',
 '訂定日誌之記錄時間週期及留存政策，並保留日誌至少六個月。',
 '系統之漏洞修復應測試有效性及潛在影響，並定期更新。',
 '建立帳號管理機制，包含帳號之申請、建立、修改、啟用、停用及刪除之程序。',
 '資通系統閒置帳號應禁用。',
 '資通系統於日誌處理失效時，應採取適當之行動。',
 '依據日誌儲存需求，配置所需之儲存容量。',
 '資通系統應識別及鑑別使用者，並禁止使用者使用共用帳號。',
 '執行「弱點掃描」安全檢測。',
 '使用密碼進行驗證時，應強制最低密碼複雜度；依機關密碼效期規定變更密碼。',
 '身分驗證相關資訊不以明文傳輸。',
 '採最小權限原則，僅允許使用者(或代表使用者行為之程序)依機關任務及業務功能，完成指派任務所需之授權存取。',
 '確保資通系統有記錄特定事件之功能，並決定應記錄之特定資通系統事件。',
 '資通系統應使用系統內部時鐘產生日誌所需時戳，並可以對應到世界協調時間(UTC)或格林威治標準時間(GMT)。',
 '系統內部時鐘應定期與基準時間源進行同步。',
 '發生錯誤時，使用者頁面僅顯示簡短錯誤訊息及代碼，不包含詳細之錯誤訊息。',
 '密碼變更時，至少不可以與前三次使用過之密碼相同。',
 '使用者輸入資料合法性檢查應置放於應用系統伺服器端。',
 '使用預設密碼初次登入系統時，應於登入後立即變更。']

### Choose the specifc raw,

In [12]:
selected_rows = [
    "建立帳號管理機制，包含帳號之申請、建立、修改、啟用、停用及刪除之程序。",
    "資通系統閒置帳號應禁用。",
]
print(f"Selected rows: {selected_rows}")

Selected rows: ['建立帳號管理機制，包含帳號之申請、建立、修改、啟用、停用及刪除之程序。', '資通系統閒置帳號應禁用。']

### Choose the Specific columns to compare

In [13]:

common_columns = [col for col in common_columns if col not in key_col]

print(common_columns)
selected_columns = [
    "符合性或不適用情況說明",
]

['符合性或不適用情況說明', '類別']

### Compare raw value

In [14]:
def compare_multiple_values(word_df, excel_df, key_col, selected_rows, selected_columns):
    results = []

    for row_key in selected_rows:
        # Per raw in selected_rows -> find matching raws in both DataFrames based on key_col
        word_match = word_df[
            word_df[key_col].astype(str).str.strip() == str(row_key).strip()
        ]

        excel_match = excel_df[
            excel_df[key_col].astype(str).str.strip() == str(row_key).strip()
        ]

        for col in selected_columns:
            # Then find the value in selected_columns, if the column doesn't exist, mark as "Word/Excel 找不到列"
            
            if word_match.empty:
                word_value = None
                status = "Word 找不到列"
            else:
                word_value = word_match[col].iloc[0]
                status = "可比較"


            if excel_match.empty:
                excel_value = None
                status = "Excel 找不到列"
            else:
                excel_value = excel_match[col].iloc[0]



            if word_match.empty or excel_match.empty:
                is_equal = False
            else:
                is_equal = str(word_value).strip() == str(excel_value).strip()

            results.append({
                "主要欄位": key_col,
                "列名稱": row_key,
                "比對欄位": col,
                "Word值": word_value,
                "Excel值": excel_value,
                "是否相同": is_equal,
                "狀態": status,
            })

    return pd.DataFrame(results)

In [15]:
result_df = compare_multiple_values(
    word_df=word_df,
    excel_df=excel_df,
    key_col="安全控制措施",
    selected_rows=selected_rows,
    selected_columns=selected_columns
)

result_df

,主要欄位,列名稱,比對欄位,Word值,Excel值,是否相同,狀態
0,安全控制措施,建立帳號管理機制，包含帳號之申請、建立、修改、啟用、停用及刪除之程序。,符合性或不適用情況說明,帳號權限異動時填列申請表，並至後臺系統維護帳號資料。\n帳號申請、修改權限與停用均需經事先申...,帳號權限異動時填列申請表，並至後臺系統維護帳號資料。\n帳號申請、修改權限與停用均需經事先申...,True,可比較
1,安全控制措施,資通系統閒置帳號應禁用。,符合性或不適用情況說明,每半年之正式帳號清查，若超過半年未使用之帳號會將之停用。,每半年之正式帳號清查，若超過半年未使用之帳號會將之停用。,True,可比較

In [16]:
from pathlib import Path
from adapters.word_table_adapter import WordTableAdapter
from adapters.excel_table_adapter import ExcelTableAdapter
from utils.table_comparactor import TableComparator
from utils.excel_handler import ExcelHandler


def main():
    word_path =  INPUT_DIR / "03.資通系統防護基準_佐證資料_農業統計資料管理系統_(普)_(奕祥資訊股份有限公司) v4_A3版_修3.docx"
    word_adapter = WordTableAdapter(word_path)
    word_df = word_adapter.load()
    print(word_df.head())

    excel_path =  INPUT_DIR / "02.防護基準評估表.xlsx"
    excel_adapter = ExcelTableAdapter(excel_path)
    excel_df = excel_adapter.load()
    ## Excel preprocessing : 1. Drop '安全控制措施', 2. Drop rename '安全控制措施說明' as '安全控制措施'
    excel_df = (
            excel_df
            .drop(columns=["安全控制措施"])
            .rename(columns={"安全控制措施說明": "安全控制措施"})
            .reindex(columns=excel_df.columns)
            )
    comparactor = TableComparator(word_df, excel_df)
    print(comparactor.find_common_columns())
    print(comparactor.get_common_raw_keys(key_col="安全控制措施"))
    print(comparactor.get_rest_of_cols())


    # get selects options
    selected_rows = [
    "建立帳號管理機制，包含帳號之申請、建立、修改、啟用、停用及刪除之程序。",
    "資通系統閒置帳號應禁用。",
    ]
    print(f"Selected rows: {selected_rows}")

    selected_columns = [
        "符合性或不適用情況說明",
    ]
    print(f"Selected columns: {selected_columns}")


    # get result dataframe
    result_df = comparactor.compare_multiple_values(selected_rows, selected_columns)
    print(result_df)

In [17]:
result_df

,主要欄位,列名稱,比對欄位,Word值,Excel值,是否相同,狀態
0,安全控制措施,建立帳號管理機制，包含帳號之申請、建立、修改、啟用、停用及刪除之程序。,符合性或不適用情況說明,帳號權限異動時填列申請表，並至後臺系統維護帳號資料。\n帳號申請、修改權限與停用均需經事先申...,帳號權限異動時填列申請表，並至後臺系統維護帳號資料。\n帳號申請、修改權限與停用均需經事先申...,True,可比較
1,安全控制措施,資通系統閒置帳號應禁用。,符合性或不適用情況說明,每半年之正式帳號清查，若超過半年未使用之帳號會將之停用。,每半年之正式帳號清查，若超過半年未使用之帳號會將之停用。,True,可比較